name: Deploy frontend on push/merge to main

on:
  push:
    branches:
      - develop
    paths:
      - 'apps/frontend/**'

  pull_request:
    types: [closed]
    branches:
      - develop
    paths:
      - 'apps/frontend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Log if workflow is working
        run: echo "apps/frontend deploy workflow is working"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build apps/frontend
        run: pnpm exec nx run frontend:build --configuration=production --skip-nx-cache

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_DEPLOYER_PRIVATE_KEY }}

      - name: Copy files to VPS
        run: |
          rsync -avz -e \
            "ssh -o StrictHostKeyChecking=no" \
            ./dist/apps/frontend/browser/* \
            ${{ secrets.VPS_DEPLOYER_USERNAME }}@${{ secrets.VPS_HOST_IP }}:/var/www/finance-tracker-frontend/
